spring.application.name=AskAi
spring.ai.retry.exclude-on-http-codes=429
spring.ai.openai.api-key=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